### ISSUE TITLE
Plot distribution of functional scores separating intended and unintended mutations

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#110]
@jbloom this is in relation to one reviewers comment requesting functional score distributions to also be separated by intended vs unintended mutations. We would potentially expect the distribution of variants with multiple unintended mutations to be more negative compared to similar mutants with multiple intended mutations. I don't really know if we want this in the main pipeline as most libraries don't have intended/unintended separation.

**Comment by jbloom** [comment]
@Bernadetadad, this issue is addressed, and the latest version (1.4.2) should make the plot you want once you update the pipeline in your repo.

Note that this improvement is on top of other changes that have been made to the pipeline of the last few months. I believe the main change of relevance will be updating `polyclonal` regularization such that some of the default regularization parameters may have changed. You might therefore make sure you are setting all regularization parameters in your `polyclonal_config.yaml` to keep them what they were before so you are getting the same results for antibody escape. If you need help, let me know.
