### ISSUE TITLE
altair png plot quality

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#116]
Is it possible to make the png download for altair plots higher quality? resolution is very low.

**Comment by jbloom** [comment]
If you are doing it with `chart.save` you might be able to do it with the `scale` option discussed [here](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format).

Otherwise if you are doing it interactively with the three dot on the upper left of the chart, I think the best option is just to download a SVG, open in Inkscape (or Illustrator), and then convert to PNG or JPG. I don't think `altair` provides a way to do this otherwise via the three dot download.
