### ISSUE TITLE
post-selection barcode count filter

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#144]
We currently have a filter that requires `no-antibody_barcode_count > 20`. I think it would be preferable if we would add an OR condition that would prevent us from dropping barcodes that have low pre-selection counts but very high post-selection counts, which probably still indicates strong selection for a variant.  It could be an absolute number or something like 10-fold increase in barcode_count post-selection. 
[barcode_count_plot_360C.html.zip](https://github.com/dms-vep/dms-vep-pipeline/files/11019091/barcode_count_plot_360C.html.zip)

**Comment by jbloom** [comment]
This issue is now addressed in #145. Others (@fwelsh @caelanradford @Caleb-Carr @bblarsen-sci) using this pipeline in addition to @Bernadetadad, I would also suggest you start using these new options. They should help, can you report back here either way if they do or do not.

See here for a detailed description: https://github.com/dms-vep/dms-vep-pipeline/pull/145#issue-1640164079

**Comment by fwelsh** [comment]
@jbloom I've run the pipeline with the following parameters:
```
prob_escape_min_antibody_counts: 30 # 2x the min_no_antibody_counts threshold
prob_escape_min_antibody_frac: 0.00004 # set to 2/libB size (50k variants)
```

This has not made much of a difference in my results. I can do some more followup analysis, but it looks like there are not many variants in my data that have low pre-selection counts but high post-selection counts. Ex: there were **27,933 variants** above the threshold for libB AUSAB-13 selections with the old pipeline. Variant counts with the updated antibody_count thresholds are:

<img width="266" alt="Screen Shot 2023-03-28 at 2 54 00 PM" src="https://user-images.githubusercontent.com/55769268/228375416-4464f28b-0ad5-4449-8261-73ef5cb7cd10.png">

The uncensored avg_prob_escape curve is noticeably cleaner with the updated pipeline (second image) compared to the original:

![visualization - 2023-03-28T145531 340](https://user-images.githubusercontent.com/55769268/228375832-4d970f21-f953-4737-9c58-74ec1957cf42.svg)

![visualization - 2023-03-28T145540 476](https://user-images.githubusercontent.com/55769268/228375849-8c7b5766-478f-418b-b18d-462930aa7e41.svg)

But not much noticeable change in the escape plots. I'll continue messing around with the parameters, lowering them more could help. But overall I'd say this has a very minor, positive effect on the H3 analysis.

**Comment by jbloom** [comment]
Interesting. I guess @Bernadetadad posted this somewhere else (@Bernadetadad, not sure where you posted it, but can you add information here), but she finds it helps to have the antibody count thresholds substantially higher.

**Comment by fwelsh** [comment]
My guess is that this has to do with library bottlenecking. In an even, diverse library, you would expect a greater number of variants that are at very low counts in the no-Ab selections, and then pop up to higher counts in the Ab selections. But if I'm bottlenecking at the selection step (which is unavoidable due to how skewed the library is), those minor variants are not going to show up in either the no-Ab or selection conditions. So adding the second antibody-count threshold only catches ~100 extra variants, since this scenario is rare in my libraries. Seems to be the most likely explanation.

**Comment by Bernadetadad** [comment]
Depending on sera, I find it adds between 100-1000 additional variants that pass threshold specifically to the two highest concentrations used (which probably makes sense as that's where the selection is strongest). But my settings are more stringent than what @fwelsh used (`prob_escape_min_antibody_counts: 100` & `prob_escape_min_antibody_frac: 0.0001`) but I don't want to go for lower counts as it definitely made antibody data noisier.

**Comment by Bernadetadad** [comment]
The addition of those even those few barcodes does make a difference for how escape probabilities look:
Without `prob_escape_min_antibody_counts/frac`:
![image](https://user-images.githubusercontent.com/22810662/228678188-66d28537-42f0-4e9d-848c-31341e916fcc.png)
with `prob_escape_min_antibody_counts: 100` & `prob_escape_min_antibody_frac: 0.0001` (added ~700 barcodes to the two higher concentrations):
![image](https://user-images.githubusercontent.com/22810662/228678349-f6672995-0d11-42d8-b1a9-c9843ac964bc.png)
This makes sense but just wanted to note.
