### ISSUE TITLE
rendering issues

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#53]
Since the last pipeline update there's some Javascript rendering issue on a bunch of altair charts
<img width="1085" alt="Screen Shot 2022-08-08 at 11 59 34 AM" src="https://user-images.githubusercontent.com/22810662/183493864-7388334a-fb90-4f86-895c-0703cf3357ec.png">
This is Chrome specific because it works on Safari (and not a browser chase issue because multiple people are seeing this too).

**Comment by WillHannon-MCB** [comment]
This is an issue with [`polyclonal`](https://github.com/jbloomlab/polyclonal) and the way both [`polyclonal.plot.mut_escape_heatmap()`](https://jbloomlab.github.io/polyclonal/_modules/polyclonal/plot.html#mut_escape_heatmap) and [`polyclonal.polt.mut_escape_lineplot()`](https://jbloomlab.github.io/polyclonal/_modules/polyclonal/plot.html#mut_escape_lineplot) handle sorting the protein site values on the x-axis. 

Essentially, if you try to sort an ordinal axis using a list specifying the desired order, you are limited to fewer than ~1000 values in Chrome. Anything greater than this will cause the `Maximum call stack size exceeded` error that @Bernadetadad  is seeing above. Other browsers like Safari and Firefox have larger (2-3X) maximum stack sizes and don't have this issue. 

@jbloom  points out in [an issue](https://github.com/altair-viz/altair/issues/2663) on [`Altair`](https://github.com/altair-viz/altair) that you can recreate this with a simple example: 

```
n = 1001 

df = pd.DataFrame({"site": map(str, range(n)), "value": 1, "order": map(int, range(n))})

(
    alt.Chart(df)
    .encode(
        x=alt.X("site:O", sort=list(range(n))), # Order by a list 
        y="value",
    )
    .mark_point()
)
```

I think this is happening because of how `Vega` parses the plot's JSON specification. The full stack trace looks like this:

```
RangeError: Maximum call stack size exceeded
    at Function (<anonymous>)
    at XB (vega@5:formatted:26374:19)
    at Object.parameter (vega@5:formatted:26379:27)
    at eT.parameterExpression (vega@5:formatted:26610:30)
    at Object.parse (vega@5:formatted:26453:46)
    at ZB (vega@5:formatted:26434:26)
    at eT.parseParameters (vega@5:formatted:26652:57)
    at eT.parseOperatorParameters (vega@5:formatted:26644:54)
    at vega@5:formatted:26628:29
    at Array.forEach (<anonymous>)
```

And there is a huge nested single-line `if else` statement stored as an expression in the plot's JSON specification that looks like this:

```
 "transform": [
        {
          "type": "formula",
      --> "expr": "datum[\"site\"]===0 ? 0 : datum[\"site\"]===1 ? 1 : (...),
          "as": "x_site_sort_index"
        }
      ]
```

I expect either the way `Vega` parses this expression is recursive or the parsed expression is recursive. If there are few enough values, this resolves without maxing out calls to the stack. If too many values (>1000) exist, the number of calls exceeds the stack size. 

Now, *here is my solution*, and perhaps @jbloom already tried this. I suggest that instead of specifying the order of the axis with a list passed to `x=alt.X("site:O", sort=list(...)`, you instead sort the sites using a numerical column in the dataframe like this:

```
(
    alt.Chart(df)
    .encode(
        x=alt.X("site:O", sort=alt.EncodingSortField(field="order", order ='ascending')),
        y="value",
    )
    .mark_point()
)
```

where `order` is a column's name in the dataframe specifying the desired order of the sites on the x-axis.

**Comment by jbloom** [comment]
@WillHannon-MCB, this is great, and seems to fix the issue. I will implement.

Note that I still get some error in the example if I make `n` large enough, such as `n = 10000`. But it's a different error: plot just doesn't show, and hopefully that error won't affect proteins of lengths we care about.
