### ISSUE TITLE
Calculate IC50 values 

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#60]
Would be good to calculate IC50 values using polyclonal so that we could compare them to real neut IC50s.

**Comment by jbloom** [comment]
This is an important addition, but since it will vary from analysis to analysis, I think it is better done as part of the repo-specific `Snakefile` rather than in `dms-vep-pipeline`.

I have added this comparison between the `polyclonal` predicted IC50s (from the biophysical model) and actual measurements to the BA.1 repo as an example in [this pull request](https://github.com/dms-vep/SARS-CoV-2_Omicron_BA.1_spike_DMS/pull/15).

@Bernadetadad, you can expand this for your repos. @caelanradford  @fwelsh @Caleb-Carr, also take a look for your repos as you may want to do the same.
