### ISSUE TITLE
Exclude samples from average antibody escape calculation

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#65]
@jbloom do you think it’s best to just remove antibody replicates that are too noisy for averaging antibody escape or should we have something in `polyclonal_config.yaml `that would indicate in such case which replicates to use for averaging?

In some cases I have 4 replicates for a single antibody, some of which are clearly noisy and I think it’s best to not use those for average antibody escape calculations. 

In some ways these noisy samples are still useful data and I don't really want to just delete them, but I don't think they should be used for average escape calculation.

**Comment by jbloom** [comment]
@Bernadetadad: What about just setting the `exclude_after_counts` in `barcode_runs` (or removing altogether)? I guess my feeling is that it makes it confusing if the pipeline fits the `polyclonal` models etc to them, and then just excludes them at the end. I totally understand about some samples being problematic which is why we have the `exclude_after_counts` option in `barcode_runs`, but I sort of feel like if we are excluding them we should just exclude them rather than include them in all steps until the averaging? This just seems like a cleaner criteria: a sample is either good enough to include or it isn't, rather than that it is sort of partially included but then dropped from average?

I am fine still adding such an option if you disagree, but my argument would be for above.

**Comment by Bernadetadad** [comment]
Then I think I would rather just remove them altogether because they don't have issue with counts which is what `exclude_after_counts` is for. That's what I'll do then
