### ISSUE TITLE
Functional score floors should probably be tested / implemented 

### ISSUE THREAD

**Issue by caelanradford** [dms-vep/dms-vep-pipeline#66]
Due to noise in pre/post counts and bottlenecking, there is a wide range of very negative functional scores in our data. This can cause strange distributions for mutations we would expect to be very negative, like stop codons. In reality, all or most of these mutations probably have the same phenotype of not being functional. 

We should test implementing a floor on functional scores, perhaps as some quantile of stop codon effect. This may or may not actually help when trying to fit models of functional effects of mutations, as having many variants with the same score may cause artifacts in the fitting.

**Comment by jbloom** [comment]
@caelanradford, I closed this issue as #76 now adds an option for `func_scores_floor` to the `config.yaml`. However, we should still test if that floor actually helps the global epistasis models fit better functional effects!

Ideally, that should be tested on your HIV data, @Bernadetadad's spike data, and @Caleb-Carr's LASV GP data. However, we don't have an immediate way of assessing if it's "better" so this will probably require some visual inspection of results with different cutoffs.

If you do determine a cutoff helps, please note here as we should in that case change default in `test_example` here to be a cutoff rather than current value of `null`.
